# Generated by Django 4.2.4 on 2023-09-01 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date_of_post', models.DateTimeField(default=datetime.datetime(2023, 9, 1, 15, 50, 1, 582109, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
