# Generated by Django 4.2.4 on 2023-09-01 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_post',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
